### ISSUE TITLE
KiCad plot options

### ISSUE THREAD

**Issue by Visne** [KarlK90/yaemk-split-kb#10]
Thanks for this nice layout and the awesome documentation.

I'm trying to remove the logo from the silkscreen (I think I would like the 'clean' look), but I'm not sure how I should plot the gerber/drill files.

For refernce, these are the defaults for gerbers:

![image](https://user-images.githubusercontent.com/39844191/177006777-df0dfbf4-997c-432b-bb25-c5b1594b9b8b.png)

And for drill files:

![image](https://user-images.githubusercontent.com/39844191/177006813-0062d7f3-ef46-409a-9e88-9b70ffb1b906.png)

Thanks!

**Comment by Visne** [comment]
Also, this is asked when plotting:

![image](https://user-images.githubusercontent.com/39844191/177006907-ad8977f6-13be-4eaf-9649-e616c0326dde.png)

I assume I should just click Refill, but better to be sure.

**Comment by Visne** [comment]
The [JLCPCB support page](https://support.jlcpcb.com/article/194-how-to-generate-gerber-and-drill-files-in-kicad-6) seems to be quite clear on what option are required, however with the current .kicad_pcb file I seem to have no F_Paste layer.

**Comment by KarlK90** [comment]
> Thanks for this nice layout and the awesome documentation.

@Visne Thank you! Somehow I didn't got your message as a notification. The paste layer is not necessary, it will be derived from the solder mask layer. Please check your drill settings, you selected inches instead of millimeters.

**Comment by Visne** [comment]
@KarlK90 Thanks, then I will order them soon!
