### ISSUE TITLE
Case SVG creation method

### ISSUE THREAD

**Issue by TheZoq2** [KarlK90/yaemk-split-kb#12]
Hi! Thanks for making this amazing and well documented keyboard. I had some extra requirements, so I ended up adding another 2 switches, and moving 2 of the columns a bit.

However, this means the case won't fit, so I'm curious if you have some method for generating the case svg from kicad, or if you just did it by hand.

**Comment by KarlK90** [comment]
@TheZoq2 Thanks for the kind words! I've actually played around quite a bit with the stm32 rust hal crates, so I can give my thanks right back. To your question the SVGs for the cases are directly exported from the KiCAD files, the user layers (I don't recall the exact name) have the cutouts for the switches in 0.1mm kerf and without kerf. For completeness you also need the edge cuts layer. Then it is just a matter of keeping the right elements in the exported svg.

**Comment by TheZoq2** [comment]
Nice, that sounds simple enough, thanks!

Also, perhaps you'd be interested to know that I run rust on my yaemk https://gitlab.com/TheZoq2/yayaemk :)

**Comment by KarlK90** [comment]
Nice, I hope you enjoy your yayaemk!
