### ISSUE TITLE
Incorrect format in BOM file PCB/assembly/YAEMK_bom.csv

### ISSUE THREAD

**Issue by siu** [KarlK90/yaemk-split-kb#3]
These days I tried to place an order in JLCPCB and the SMT process was failing with the message:

```
Incorrect format
No valid content found.
```

Support told me that the BOM file was missing a header, adding the following in the first line of `PCB/assembly/YAEMK_bom.csv` fixes the import:

`Comment,Designator,Footprint,JLCPCB Part`

Thanks again for sharing the YAEMK design and the great documentation.

**Comment by KarlK90** [comment]
Corrected that, thanks!
