### ISSUE TITLE
[question] Compatible component replacements?

### ISSUE THREAD

**Issue by siu** [KarlK90/yaemk-split-kb#4]
I am trying to order the YAEMK from JLCPCB and currently three parts are out of stock:

- The microcontroller, this is already documented, I will source it from somewhere else
- ON Semiconductor CAT24C512YI-GT3 https://www.lcsc.com/product-detail/EEPROM_ON-Semiconductor-CAT24C512YI-GT3_C56096.html
- 3PEAK LMV321TP-TR https://www.lcsc.com/product-detail/Operational-Amplifier_3PEAK-LMV321TP-TR_C90297.html

I would like to replace these by other compatible parts, I found the two that follow but I don't have enough experience with electronics to know if these are really compatible:

- BL(Shanghai Belling) BL24C512A-SFRC (https://www.lcsc.com/product-detail/EEPROM_BL-Shanghai-Belling-BL24C512A-SFRC_C169114.html)
- Shanghai Mingda Microelectronics MD1621 (https://www.lcsc.com/product-detail/Operational-Amplifier_Shanghai-Mingda-Microelectronics-MD1621_C126981.html)

I would appreciate if you could confirm that these are compatible (or not).

**Comment by KarlK90** [comment]
The EEPROM and OP-amps are pin-compatible and I'm very certain that they are functionally equivalent! If any of the components should fail there will be a workaround, as the plug detection can be disabled and the internal EEPROM emulation is now available for the GD32VF103.

**Comment by KarlK90** [comment]
I have added an alternate BOM with those components and linked it in the build guide. Thank you.

**Comment by siu** [comment]
Hi @KarlK90, I am happy to share that I ordered and built the keyboards, they work perfectly with the replacement components, yay! For the MCU I chose the RISC-V in the Longan Nano, desoldered and soldered it in the boards. The MCU and USB connectors are hard to solder but it is doable with decent tools and patience. I did not install any of the LED lights but I may add them in the future. Note that I have not tested the EEPROM yet as I don't have any real use for it, I may hack something together in the following days to check if it works.

For the programming, I was also able to set up the toolchain to build for RISC-V following the instructions, no issues at all.

The build guide is very well written and I was able to follow it even not having much experience in electronics, thanks for that!

The only thing I found confusing is the example firmware. At that stage in the build I think the interest is to check the wiring is correct.
 - I found that using the keyboard was very erratic, until I realized that it has home row modifiers. Understanding that I could check that all keys worked as expected (or not, see next point). If you agree I can upload a simpler keymap with the name "testing" to be used in the guide.
 - Keys 3 and 8 register the key below them randomly, for example tapping 3 would result in "3eee" written. I did not know if the wiring was wrong or it was a firmware issue. Anyway I continued with the programming of the board and it looks like the issue is already solved in your fork of the qmk_firmware (https://github.com/KarlK90/qmk_firmware/commit/dfb777e3d0764e0bd19d9e59b0e39b02f7c8b479 at the time of writing). Just recompiling fixed it.

I also hear the coil whine when the displays show some specific information as you reported in https://github.com/qmk/qmk_firmware/pull/10379#issuecomment-819630957.

Again, thanks for sharing the project, it is a lot of fun.

**Comment by KarlK90** [comment]
Hi @siu that is great news, happy that you have a working YAEMK now :muscle:!

>     * I found that using the keyboard was very erratic, until I realized that it has home row modifiers. Understanding that I could check that all keys worked as expected (or not, see next point). If you agree I can upload a simpler keymap with the name "testing" to be used in the guide.

You are right about the test firmware, I'll add a testing keymap and compile it as the default without homerow modifiers. 

>     * Keys 3 and 8 register the key below them randomly, for example tapping 3 would result in "3eee" written. I did not know if the wiring was wrong or it was a firmware issue. Anyway I continued with the programming of the board and it looks like the issue is already solved in your fork of the qmk_firmware ([KarlK90/qmk_firmware@dfb777e](https://github.com/KarlK90/qmk_firmware/commit/dfb777e3d0764e0bd19d9e59b0e39b02f7c8b479) at the time of writing). Just recompiling fixed it.

This is actually caused by EMI noise of the matrix lines, because the matrix scanning is rather fast on this board. To fix the issue the output pins have been assigned the slowest possible speed (which is plenty fast for this simple use-case). You can see the corresponding lines in this [commit](https://github.com/KarlK90/qmk_firmware/blob/1aced62939e4a31f283923dad6e90a948c545a1b/keyboards/karlk90/yaemk/yaemk.c#L112-L115).

> I also hear the coil whine when the displays show some specific information as you reported in [qmk/qmk_firmware#10379 (comment)](https://github.com/qmk/qmk_firmware/pull/10379#issuecomment-819630957).

Yes, these oleds are a bit on the cheap side. I already got some burn-in after one year but nothing to bad. Maybe the whine could be reduced further by swapping the coils on the board but it is not that bad I recon.  

> Again, thanks for sharing the project, it is a lot of fun.

Thanks for the kind words. :muscle::slightly_smiling_face:, wish you lots of fun with your YAEMK!

**Comment by siu** [comment]
I confirm that the replacement EEPROM works as expected, I am using it now to store the default layer between two different configurations I am experimenting with.

Closing the issue as well as the questions were already answered :)

**Comment by KarlK90** [comment]
> I confirm that the replacement EEPROM works as expected, I am using it now to store the default layer between two different configurations I am experimenting with.
> 
> Closing the issue as well as the questions were already answered :)

Great to hear that you apparently use your YAEMK. I Don't if you already did that but, if you want share you build on Reddit. 🙂
