### ISSUE TITLE
Different reset behaviour

### ISSUE THREAD

**Issue by toniz4** [KarlK90/yaemk-split-kb#7]
When reading the guide i noticed that the way of enabling the bootloader mode in the arm chip is different from the risc v chip, why so?

**Comment by KarlK90** [comment]
The GigaDevice circuitry inside the GD32VF103 is different enough from the STM32F303 that the combined Reset and BOOT0 pin triggering circuit that is operated by the DFU button doesn't work properly. So the plug / unplug procedure is needed as a workaround.

**Comment by toniz4** [comment]
Got it, thanks!
