### ISSUE TITLE
Doubt on JP1 and JP2 soldering

### ISSUE THREAD

**Issue by dnbias** [KarlK90/yaemk-split-kb#9]
Hi, thank you for the awesome work on this keyboard!

Thinking about building this I was reading through your step-by-step instructions and step 4. is not very clear to me.
You refer to JP1 and JP2 although I didn't find them on the interactive BOM and I'm not sure what you mean by
"connect the left pad with the middle pad on both jumpers via a solder bridge on the left side of the keyboard", and then mirrored on the right side. Left pad here is left in relation to what? 
I'm sorry if it's obvious but I'm new to these things :smile:

**Comment by Visne** [comment]
They are not on the BOM as they are not physical items, you just connect two pads on the PCB with solder (a solder bridge).

The two halves of the keyboard connect with each other via a cable. Both halves have an RX (receive) line and a TX (transmit) line. If you would solder both PCBs the exact same, you would end up soldering the RX of the left half to the RX of the right half, and the same for TX. This doesn't make sense, as you want the transmitting end from the left half to end up at the receiving end of the right half, and vice versa. Therefore, you have to solder both sides slightly differently.

Now, I don't fully understand "right and left pads" either, it makes more sense to call them top and bottom pads I think. If you look at the [finished left handed PCB](https://karlk90.github.io/yaemk-split-kb/#finished-left-handed-pcb-for-reference-switches-are-already-installed) you can see what's going on:

![image](https://user-images.githubusercontent.com/39844191/177008123-860752d1-1ba1-4d68-b69e-b2889b02d517.png)

Here, the two middle pads are connected to the two bottom pads.

On the right handed side of the keyboard, you would instead solder the two middle pads to the two top pads. Then, RX is connected to TX and TX is connected to RX.

**Comment by dnbias** [comment]
Thank you, that makes much more sense! I imagined it was something like that but thought I'd ask anyway.

Closing.
